<a href="https://colab.research.google.com/github/turpatijagadeeshwar/JAGADEESH/blob/main/09_NumPy_Arrays_VectorMath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 09 – NumPy – Arrays & Vector Mathematics

## 📖 Theory

**NumPy** (Numerical Python) is the foundation of scientific computing in Python.

### Why NumPy over plain lists?
| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Math ops | Manual loops | Vectorised (automatic) |
| Speed | Slow | Very fast |
| Multi-dimensional | Complex | Built-in |

A **NumPy array (ndarray)** is like a mathematical **vector** (1D) or **matrix** (2D).

**Vectorisation**: applying an operation to the entire array at once without a loop — mirrors how mathematics treats vectors.

*Install if needed: `pip install numpy`*

In [1]:
import numpy as np   # import numpy, alias it as 'np' for convenience

# ── Creating arrays ───────────────────────────────────────────────────
a = np.array([1, 2, 3, 4, 5])    # 1-D array from a Python list
b = np.array([10, 20, 30, 40, 50])

print('a         :', a)           # [1 2 3 4 5]
print('b         :', b)           # [10 20 30 40 50]
print('Shape of a:', a.shape)     # (5,) → 5 elements, 1 dimension
print('Data type :', a.dtype)     # int64 (64-bit integers)

a         : [1 2 3 4 5]
b         : [10 20 30 40 50]
Shape of a: (5,)
Data type : int64


In [2]:
# ── Vectorised arithmetic (no loops needed!) ─────────────────────────
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print('a + b  :', a + b)    # element-wise addition   [11 22 33 44 55]
print('b - a  :', b - a)    # element-wise subtraction[9 18 27 36 45]
print('a * b  :', a * b)    # element-wise product    [10 40 90 160 250]
print('b / a  :', b / a)    # element-wise division   [10. 10. 10. 10. 10.]
print('a ** 2 :', a ** 2)   # element-wise square     [1 4 9 16 25]
print('a * 3  :', a * 3)    # scalar broadcast: multiply every element by 3

a + b  : [11 22 33 44 55]
b - a  : [ 9 18 27 36 45]
a * b  : [ 10  40  90 160 250]
b / a  : [10. 10. 10. 10. 10.]
a ** 2 : [ 1  4  9 16 25]
a * 3  : [ 3  6  9 12 15]


In [3]:
# ── Array creation utilities ─────────────────────────────────────────
zeros = np.zeros(5)              # array of 5 zeros
ones  = np.ones(5)               # array of 5 ones
rng   = np.arange(0, 10, 2)      # like range(): 0, 2, 4, 6, 8
lin   = np.linspace(0, 1, 6)     # 6 evenly spaced values from 0 to 1

print('zeros   :', zeros)
print('ones    :', ones)
print('arange  :', rng)
print('linspace:', lin)

zeros   : [0. 0. 0. 0. 0.]
ones    : [1. 1. 1. 1. 1.]
arange  : [0 2 4 6 8]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]


In [4]:
# ── Statistical functions on arrays ──────────────────────────────────
data = np.array([4, 8, 15, 16, 23, 42, 55, 3])

print('Mean     :', np.mean(data))       # arithmetic average
print('Median   :', np.median(data))     # middle value
print('Std Dev  :', np.std(data).round(4))  # standard deviation
print('Variance :', np.var(data).round(4))  # variance = std²
print('Sum      :', np.sum(data))        # total
print('Min / Max:', np.min(data), '/', np.max(data))

Mean     : 20.75
Median   : 15.5
Std Dev  : 17.4768
Variance : 305.4375
Sum      : 166
Min / Max: 3 / 55


In [5]:
# ── 2-D arrays (matrices) ─────────────────────────────────────────────
# Creating a 2×3 matrix
M = np.array([[1, 2, 3],
              [4, 5, 6]])

print('Matrix M:\n', M)
print('Shape   :', M.shape)      # (2, 3) → 2 rows, 3 columns
print('Element [1][2]:', M[1,2]) # row 1, col 2 → 6

# Transpose: flip rows and columns (like Mᵀ in maths)
MT = M.T
print('Transposed MT:\n', MT)
print('New shape:', MT.shape)   # (3, 2)

Matrix M:
 [[1 2 3]
 [4 5 6]]
Shape   : (2, 3)
Element [1][2]: 6
Transposed MT:
 [[1 4]
 [2 5]
 [3 6]]
New shape: (3, 2)


### 💡 Key Takeaway
NumPy arrays allow you to write mathematical vector/matrix notation directly in code. Vectorisation eliminates explicit loops and is orders of magnitude faster. `np.linspace`, `np.arange`, and statistical functions are indispensable tools.